Update Helbiz, add others
MobilityData/gbfs pull request #472
Opened 2023-01-06 23:03 UTC by mplsmitch

Updates Helbiz to current v2.2 URLs, adds new feeds for LINK, Pony

2023-01-06 23:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MobilityData/gbfs?pullRequest=472) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MobilityData/gbfs?pullRequest=472) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MobilityData/gbfs?pullRequest=472) it.</sub>

2023-01-07 18:54 UTC, josee-sabourin requested changes
Thank Mitch! 
A few nits: 
- Pony Poitiers validator URL is incorrect. Here is the correct link: https://gbfs-validator.netlify.app/?url=https%3A%2F%2Fgbfs.getapony.com%2Fv1%2Fpoitiers%2Fen%2Fgbfs.json
- The Helbiz feeds seem to have some extra space at the end of them creating a new line

2023-01-08 17:46 UTC, mplsmitch commented
@josee-sabourin I've corrected the Pony and Helbiz entries and since I was in the neighborhood I updated all the PBSC URLs to v2.3

2023-01-09 13:00 UTC, josee-sabourin approved these changes
Excellent, thanks!

2023-01-09 13:00 UTC, merged