Add contribution form for systems.csv in README.md
MobilityData/gbfs pull request #487
Opened 2023-01-31 14:02 UTC by josee-sabourin

As discussed in #434, there is now a Google form to contribute to systems.csv which provides a Github-less opportunity to contribute. 

Note: This addition does not require a vote.

2023-02-01 19:28 UTC, emmambd requested changes
2 comments on the Google form: 

1 nit: it's cool that you can validate that the ISO code is in fact an ISO code! I would give some thought to how strict you want to be about that when our main goal is to encourage submissions. Your call, but it's worth considering just leaving it as text. 

1 bug: the Name field for the system requires an email right now.

2023-02-01 19:30 UTC, josee-sabourin commented
You're right, I've removed the data validation from that question. 

Also changed the format for name! 

thanks for the review :)

2023-02-02 08:39 UTC, futuretap commented
Do we actually need all these fields? At least in theory, filling out the GBFS feed URL should be all that’s needed since all the fields could be automatically retrieved from system_information.json. (Not sure though if/how such an automation could be done with Google forms.)

Having the validation URL as a separate entry in systems.csv is superfluous imo since it can be directly derived from the feed URL. This might be even more correct since currently, systems.csv has some broken validation URLs for Link, Helbiz and Donkey Republic.

2023-02-02 13:27 UTC, josee-sabourin commented
Hi @futuretap, currently in the form the only required field is the auto-discovery URL, if the contributor would like to provide more, they can, otherwise I will add the missing information. We currently don't have any automations to harvest this data, although we could create some in the future, but for now this is what we are working with.

In terms of validation URL, there are definitely some bugs and we are working internally to identify out the best way forward to provide validation in an easy way.

2023-02-21 13:59 UTC, emmambd reviewed
@josee-sabourin nit: the location field is required currently in the google form, as well as the auto-discovery URL.

2023-02-21 14:01 UTC, josee-sabourin commented
location fixed, auto-discovery URL remains required since we cannot add a new entry without it! All of the information not required needs to be harvested from the auto-discovery URL.

2023-02-21 14:03 UTC, emmambd approved these changes

2023-02-21 14:04 UTC, merged