Reorganize Governance and README
MobilityData/gbfs pull request #521
Opened 2023-07-12 14:50 UTC by josee-sabourin

We have heard from community members that it is difficult to understand how to participate in GBFS development. MobilityData is re-evaluating the governance and trying to make it as easy as possible for someone to participate and to understand their role as a contributor as well as MobilityData's role as a maintainer. 

This first modification does not change any governance process (and therefore does not require a vote), it simply moves the governance to it's own page (governance.md) on the repository and shows a more simple version of the governance on the README.md. 

In the coming weeks we will work to improve the layout of governance.md and propose any changes to the governance if need be.

2023-07-12 19:28 UTC, mplsmitch commented
I'm totally in favor of moving the governance to a separate document. The README needs frequent updates to things like current versions etc. that don't need to be voted on whereas any change to the governance should require a vote. Having the governance in a separate document will help with that.

I think the proposed README text could be more concise. There's some redundancy between the bullet points and the paragraph above. Here's what I would suggest:

> Comments or questions can be addressed to the community by [opening an issue](https://github.com/NABSA/gbfs/issues). Proposals for changes or additions to the specification can be made through [pull requests](https://github.com/NABSA/gbfs/pulls). Questions can also be addressed to the community via the [public GBFS Slack channel](https://bit.ly/mobilitydata-slack) or to the shared mobility staff at MobilityData: sharedmobility@mobilitydata.org. 
> 
> ### Proposing a Change 
> 
> - Anyone can propose a change to the specification by opening a pull request.
> - Proposed changes should align with the [Guiding Principles](https://github.com/MobilityData/gbfs#guiding-principles).
> - All changes are subject to a vote.
> - A proposal passes if there are at least 3 votes in favor and none opposed, with at least one vote from a GBFS producer, and one from a GBFS consumer.
> - Anyone can vote. 
> 
> If you would like to propose a change but aren’t comfortable opening a pull request, MobilityData is happy to help. Get in touch at [sharedmobility@mobilitydata.org](mailto:sharedmobility@mobilitydata.org).
> 
> For more information on the specification governance, including instructions on how and when to call a vote, see [governance.md](https://github.com/MobilityData/gbfs/blob/master/governance.md)
> 
> Find a real-world example of the governance in action [here](https://github.com/MobilityData/gbfs/pull/454).

2023-07-14 14:30 UTC, richfab commented on README.md
> +GBFS is an open source project developed under a consensus-based governance model. Contributors come from across the shared mobility industry, public sector, civic technology and elsewhere. GBFS is n
Suggestion to replace `NABSA` repo by `MobilityData` repo.

```suggestion
GBFS is an open source project developed under a consensus-based governance model. Contributors come from across the shared mobility industry, public sector, civic technology and elsewhere. GBFS is not owned by any one person or organization. The specification is not fixed or unchangeable. As the shared mobility industry evolves, it is expected that the specification will be extended by the GBFS community to include new features and capabilities over time. <br/><br> Comments or questions can be addressed to the community by [opening an issue](https://github.com/MobilityData/gbfs/issues). Proposals for changes or additions to the specification can be made through [pull requests](https://github.com/MobilityData/gbfs/pulls). Questions can also be addressed to the community via the [public GBFS Slack channel](https://bit.ly/mobilitydata-slack) or to the shared mobility staff at MobilityData: [sharedmobility@mobilitydata.org](mailto:sharedmobility@mobilitydata.org).
```

2023-07-14 14:31 UTC, richfab commented on README.md
>  MobiltyData has compiled a [project roadmap](https://github.com/NABSA/gbfs/wiki/Project-Roadmap) with a list of major features, changes and other work coming up in the near future.
Suggestion to replace `NABSA` repo by `MobilityData` repo.

```suggestion
MobiltyData has compiled a [project roadmap](https://github.com/MobilityData/gbfs/wiki/Project-Roadmap) with a list of major features, changes and other work coming up in the near future.
```

2023-07-14 14:32 UTC, richfab commented on governance.md
> +* Editorial changes as well as items that are not found in [gbfs.md](https://github.com/NABSA/gbfs/blob/master/gbfs.md) do not need to be voted on. Extensions that include new capabilities and featur
Suggestion to replace `NABSA` repo by `MobilityData` repo.

```suggestion
* Editorial changes as well as items that are not found in [gbfs.md](https://github.com/MobilityData/gbfs/blob/master/gbfs.md) do not need to be voted on. Extensions that include new capabilities and features MUST be voted on.
```

2023-08-02 17:59 UTC, richfab commented on README.md
> +* Discussions on pull requests must be a minimum of seven calendar days.
Small suggestion for consistency with the line below.

```suggestion
* Discussions on pull requests must be a minimum of 7 calendar days.
```

2023-08-02 18:03 UTC, richfab requested changes
LGTM! Added one small formatting suggestion.

2023-08-02 18:20 UTC, richfab approved these changes
LGTM 🚀

2023-08-02 18:20 UTC, merged