Updates systems.csv
MobilityData/gbfs pull request #549
Opened 2023-09-28 17:48 UTC by josee-sabourin

Add a few Donkey Republic, Neuron Mobility and Urban Sharing feeds

2023-09-28 18:06 UTC, mplsmitch requested changes

2023-09-28 18:06 UTC, mplsmitch commented on systems.csv
> +NL,Donkey Reopublic Gorinchem,"Gorinchem, NL",donkey_gorinchem,https://www.donkey.bike/,https://stables.donkey.bike/api/public/gbfs/2/donkey_gorinchem/gbfs.json,https://gbfs-validator.mobilitydata.or
Typo> Donkey Reopublic

2023-09-28 19:25 UTC, josee-sabourin commented on systems.csv
> +NL,Donkey Reopublic Gorinchem,"Gorinchem, NL",donkey_gorinchem,https://www.donkey.bike/,https://stables.donkey.bike/api/public/gbfs/2/donkey_gorinchem/gbfs.json,https://gbfs-validator.mobilitydata.or
fixed thanks!

2023-09-28 20:21 UTC, richfab approved these changes
LGTM! Even more new feeds 🤩

2023-09-29 10:45 UTC, futuretap commented
The Gorinchem [free_bike_status feed](https://stables.donkey.bike/api/public/gbfs/2/donkey_gorinchem/nl/free_bike_status.json) contains a `data` hash embedded into a `data` hash. Can this please be fixed?

2023-09-29 13:31 UTC, josee-sabourin commented
cc: @grzala

2023-10-11 12:36 UTC, merged