Add release cycles to the governance
MobilityData/gbfs pull request #579
Opened 2023-12-20 17:32 UTC by richfab

Fixes https://github.com/MobilityData/gbfs/issues/556

This PR is a proposal to:
- Add Version Release Cycles
- Add details to the voting steps

2023-12-20 17:54 UTC, josee-sabourin requested changes
LGTM - we just need to update the README to make sure things are not in two places (I'm thinking specifically of the section of Versioning).

2023-12-20 22:41 UTC, mplsmitch commented
The MINOR release line is puzzling to me. 

> MINOR releases SHOULD be released every May and November by the Maintainer.

The only time you would have a MINOR release in November is if there is no MAJOR release for that year. For example you wouldn't have a v4.0 MAJOR and a v4.1 MINOR in November.

A simpler way to say this would be:

> 
> - MINOR versions SHOULD be released every May
> - MAJOR versions SHOULD be released every November
> - In the event that there is no MAJOR version release for the period, a MINOR version MAY be released in November.

2023-12-21 14:54 UTC, josee-sabourin approved these changes

2024-01-03 14:22 UTC, richfab commented
I hereby call a vote on this proposal. Voting will be open for 10 full calendar days until 11:59PM UTC on Saturday, 13th January 2024.
Please vote for or against the proposal, and include the organization for which you are voting in your comment.
Please note if you can commit to implementing the proposal.

2024-01-03 21:03 UTC, testower commented on governance.md
> +The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED", "NOT RECOMMENDED", "MAY", and "OPTIONAL" in this document are to be interpreted as described
"key words" => "keywords"

2024-01-03 21:12 UTC, mplsmitch commented on governance.md
> +The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED", "NOT RECOMMENDED", "MAY", and "OPTIONAL" in this document are to be interpreted as described
I agree, however, that text  including "key words" comes directly from rfc2119 and rfc1874

2024-01-03 21:16 UTC, testower commented on governance.md
> +The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED", "NOT RECOMMENDED", "MAY", and "OPTIONAL" in this document are to be interpreted as described
I see dictionaries don't agree among themselves either. I'm fine with just leaving it as is

2024-01-04 14:16 UTC, futuretap commented
+1 from Where To?

2024-01-08 14:20 UTC, cmonagle commented
+1 from Transit

2024-01-11 08:41 UTC, richfab commented
Voting on this PR closes in 2 calendar days. Please vote for or against the proposal, and include the organization for which you are voting in your comment.

2024-01-11 09:48 UTC, BredeD commented
+1 from Entur

2024-01-15 09:28 UTC, richfab commented
This vote has now closed, and it passes!

Votes in favor:
Where To? (consumer)
Transit app (consumer)
Entur (producer)
 
There were no votes against.

This change will take effect immediately. Note that this does not affect v3.0-RC2 which is already released and ready for implementation!

2024-01-15 13:58 UTC, davidgamez approved these changes

2024-01-15 14:00 UTC, merged